<a href="https://colab.research.google.com/github/Chae-rin-Park/class2021Spring/blob/main/20210426.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from matplotlib import pyplot as plt
import numpy as np
import IPython.display as ipd
from scipy.signal import lfilter

In [30]:
def phasor (amp, sr, dur, freq):
  t = np.arange (1, sr*dur+1)/sr
  theta = t * 2*np.pi * freq
  s = np.sin (theta)
  return t, theta, s

In [36]:
phasor (1, 10000, 2, 440)

(array([1.0000e-04, 2.0000e-04, 3.0000e-04, ..., 1.9998e+00, 1.9999e+00,
        2.0000e+00]),
 array([2.76460154e-01, 5.52920307e-01, 8.29380461e-01, ...,
        5.52865015e+03, 5.52892661e+03, 5.52920307e+03]),
 array([ 2.72951936e-01,  5.25174630e-01,  7.37513117e-01, ...,
        -5.25174630e-01, -2.72951936e-01,  1.25522677e-13]))